### ISSUE TITLE
[Question] wandb.sdk.lib.config_util.ConfigError when using exp_grid

### ISSUE THREAD

**Issue by 1Asan** [OmniSafeAI/omnisafe#129]
### Required prerequisites

- [X] I have read the documentation <https://omnisafe.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/PKU-MARL/omnisafe/issues) and [Discussions](https://github.com/PKU-MARL/omnisafe/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/PKU-MARL/omnisafe/discussions/new).

### Questions

First, Thanks for this well-designed library, it is elegant and reliable.
Yesterday, When I start a set of experiments, I found a strange ERROR, I am not sure whether it is a bug.
This is my core configuration for running, the other part is as same as your example in omnisafe/examples/benchmarks:
```python
    eg = ExperimentGrid(exp_name='Test')
    eg.add('algo', ['PPOLag'])
    eg.add('env_id', ['SafetyPointGoal0-v0', 'SafetyPointGoal1-v0', 'SafetyPointGoal2-v0', 'SafetyAntVelocity-v4'])
    eg.add('epochs', 20)
    # eg.add('actor_lr', [0.001, 0.003, 0.004], 'lr', True)
    # eg.add('actor_iters', [1, 2], 'ac_iters', True)
    eg.add('wandb_project', 'test')
    eg.add('num_envs', [1, 2, 4, 8, 16, 32])
    # eg.add('seed', [0, 5, 10])
    eg.run(train, num_pool=10)
```

This is the information which wandb throw:
![image](https://user-images.githubusercontent.com/99461435/222873320-ea2af8f0-7c98-45be-bc75-5a7468f8daaa.png)

**Comment by zmsn-2077** [comment]
Feel free to ask to reopen this if you have more questions.
