### ISSUE TITLE
[BUG] Errors about CLI

### ISSUE THREAD

**Issue by u21h2** [OmniSafeAI/omnisafe#189]
### Required prerequisites

- [X] I have read the documentation <https://omnisafe.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/PKU-MARL/omnisafe/issues) and [Discussions](https://github.com/PKU-MARL/omnisafe/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/PKU-MARL/omnisafe/discussions/new).

### What version of OmniSafe are you using?

0.2.2

### System information

3.9.13 (main, Aug 25 2022, 18:29:29)
[Clang 12.0.0 ] darwin
0.2.2

### Problem description

<img width="1305" alt="image" src="https://user-images.githubusercontent.com/24861470/228560676-f5203c5c-b30b-41b5-8bde-c7abf6d7aea3.png">

When use `omnisafe benchmark --help`, i run the example command provided by omnisafe, this bug happens. 

### Reproducible example code

The Python snippets:

```python

```

Command lines:

```bash

```

Extra dependencies:

```text

```

Steps to reproduce:

1.
2.
3.

**Comment by zmsn-2077** [comment]
We just tested it, and it works fine with the default entry in the `examples`, this may be an alternative for you who want to use `OmniSafe` quickly. We didn't update the description in `typer` in time, this is our oversight. We will propose a PR to fix this issue as soon as possible.

**Comment by muchvo** [comment]
Hi, sorry for the late reply. For the required arguments, users should input them in positional order instead of using `--key value`. For the case you encountered, you should try
```bash
omnisafe benchmark exp-1 1 ./configs/on-policy/PPOLag.yaml --log_dir ./runs
```

**Comment by muchvo** [comment]
If the issue still exists, feel free to reopen it.
