### ISSUE TITLE
[BUG] Omnisafe cannot run on a Mac M1 device

### ISSUE THREAD

**Issue by u21h2** [OmniSafeAI/omnisafe#190]
### Required prerequisites

- [X] I have read the documentation <https://omnisafe.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/PKU-MARL/omnisafe/issues) and [Discussions](https://github.com/PKU-MARL/omnisafe/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/PKU-MARL/omnisafe/discussions/new).

### What version of OmniSafe are you using?

0.2.2

### System information

3.9.13 (main, Aug 25 2022, 18:29:29)
[Clang 12.0.0 ] darwin
0.2.2

### Problem description

Admittedly, this is a very nice library. However, Omnisafe has the following bug when i run the following command `omnisafe train --algo PPO --total-steps 1024 --vector-env-nums 1 --custom-cfgs algo_cfgs:update_cycle --custom-cfgs 512 --device cpu`.
<img width="1074" alt="image" src="https://user-images.githubusercontent.com/24861470/228565259-a2c35041-a440-4f66-aecc-6ad90fef6a64.png">
Note: My device is MacBook Pro M1 Pro. 

### Reproducible example code

The Python snippets:

```python

```

Command lines:

```bash

```

Extra dependencies:

```text

```

Steps to reproduce:

1.
2.
3.

**Comment by zmsn-2077** [comment]
We have not tested on the `Mac` platform before, but it seems necessary to support `Mac` and Windows platforms, we will start testing on the `Mac` platform as soon as possible and give a solution.

**Comment by zmsn-2077** [comment]
Thank you for providing your invaluable feedback. We would like to inform you that the `OmniSafe` repo has undergone an intense refactoring process over the past two weeks. The crux of OmniSafe is `PyTorch` and `Safety-Gymnasium`, with the former enjoying extensive support from its user community on Mac M-series chips. Our team has conducted an exhaustive examination of the Safety-Gymnasium's compatibility with Mac, and we are pleased to report that OmniSafe can now be trained on the Mac's M1 chip. Our detailed results were obtained using the `macOS Ventura 13.3.1 and Apple M1 Max platform for testing`.

![image](https://user-images.githubusercontent.com/73586554/232467367-239c6a1c-415e-4f0a-926a-38ecb932432b.png)

If you meet the following error, 
> RuntimeError: No ffmpeg exe can be found. Install `ffmpeg` on your system, or set the IMAGEIO_FFMPEG_EXE environment variable.
you can paste the following code into gymnasium/utils/save_video.py after `from gymnasium import logger`
```
import os
os.environ["IMAGEIO_FFMPEG_EXE"] = "/usr/bin/ffmpeg"
```

**In addition to that, following OmniSafe's installation instructions, you can train your SafeRL model on MacOS.**
