### ISSUE TITLE
[BUG] When I enable `smooth` in statistics tools, costs are skipped.

### ISSUE THREAD

**Issue by 1Asan** [OmniSafeAI/omnisafe#207]
### Required prerequisites

- [X] I have read the documentation <https://omnisafe.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/PKU-MARL/omnisafe/issues) and [Discussions](https://github.com/PKU-MARL/omnisafe/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/PKU-MARL/omnisafe/discussions/new).

### What version of OmniSafe are you using?

0.3.0

### System information

ubuntu 20.04
0.3.0

### Problem description

When I enable `smooth` in statistics tools, costs are skipped.
Before enabling smooth:
![before](https://user-images.githubusercontent.com/99461435/230622997-77063ade-f1c2-406b-b3f2-cf7d8aac4307.png)
After enabling smooth:
![after](https://user-images.githubusercontent.com/99461435/230623056-76d56d89-6d73-41ef-ab85-306456c6abde.png)

### Reproducible example code

The Python snippets:

```python

```

Command lines:

```bash

```

Extra dependencies:

```text

```

Steps to reproduce:

1.plot without smooth
2.enable smooth and plot
3.

### Expected behavior

Smooth in all graphs

**Comment by muchvo** [comment]
Thanks for your feedback, we also noticed that. And it was fixed in #208.
