### ISSUE TITLE
[Question] Shouldn't tanh usually be the output activation function in PPO or TRPO?

### ISSUE THREAD

**Issue by Obnayuf** [OmniSafeAI/omnisafe#222]
### Required prerequisites

- [X] I have read the documentation <https://omnisafe.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/OmniSafeAI/omnisafe/issues) and [Discussions](https://github.com/OmniSafeAI/omnisafe/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/OmniSafeAI/omnisafe/discussions/new).

### Questions

Why is the output activation function of the mean layer in gaussian_learning_actor.py defaulted to nn.identity? Shouldn't tanh usually be the output activation function in PPO or TRPO?

**Comment by Gaiejj** [comment]
This is a very good question, and we also took this into account when implementing the PPO algorithm in omnisafe. After our research, in Spinning up https://github.com/openai/spinningup/blob/master/spinup/algos/pytorch/ppo/core.py, Tianshou https://github.com/thu-ml/tianshou In the implementation of /blob/master/examples/mujoco/mujoco_ppo.py and cleanrl https://github.com/vwxyzjn/cleanrl/blob/master/cleanrl/ppo_continuous_action.py, the PPO of continuous action adopts ``Linear``, ``Tanh()``, ``Linear``, ``Tanh()`` Structural implementation of ``Linear``. We also think that adding ``Tanh()`` activation function in the last layer also has better performance, but we decided to follow the mainstream implementation. We provide PPO performance curves based on this setting at https://github.com/OmniSafeAI/omnisafe/tree/main/benchmarks.
e.g. 
<img width="1086" alt="image" src="https://user-images.githubusercontent.com/108712610/233991613-1850dc23-320a-48e8-8fa0-60068ac7579d.png">

 You can also modify the activation function of the last layer. If you achieve better performance, we welcome you to propose a Pull Request to make omnisafe's implementation more trust worthy.
