### ISSUE TITLE
[Feature Request] delete the file generated in the process of pytest

### ISSUE THREAD

**Issue by zmsn-2077** [OmniSafeAI/omnisafe#228]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/OmniSafeAI/omnisafe/issues) and [Discussions](https://github.com/OmniSafeAI/omnisafe/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/OmniSafeAI/omnisafe/discussions/new).

### Motivation

During development, `make test` generates many process files, which should be deleted automatically after the test is done, thus avoiding too many modified files from git local history.
<img width="463" alt="image" src="https://user-images.githubusercontent.com/73586554/235550734-50af279f-7fc5-439e-b43a-00b1ff064497.png">

**Comment by rockmagma02** [comment]
finished in #175
